import { mutation, query } from "./_generated/server";

export const getPlants = query({
  args: {},
  handler: async (ctx) => {
    return await ctx.db.query("plants").collect();
  },
});

export const seedPlants = mutation({
  args: {},
  handler: async (ctx) => {
    const existing = await ctx.db.query("plants").collect();
    if (existing.length > 0) return { message: "Database already seeded" };

    const crops = [
      {
        name: "Tomato",
        nameAr: "طماطم",
        minMoisture: 30,
        maxMoisture: 70,
        minSalinity: 1.0,
        maxSalinity: 2.5,
        optimalTemp: 25,
        description: "Requires consistent moisture.",
      },
      {
        name: "Cucumber",
        nameAr: "خيار",
        minMoisture: 40,
        maxMoisture: 80,
        minSalinity: 1.0,
        maxSalinity: 2.0,
        optimalTemp: 22,
        description: "High water demand.",
      },
      {
        name: "Potato",
        nameAr: "بطاطس",
        minMoisture: 20,
        maxMoisture: 60,
        minSalinity: 1.5,
        maxSalinity: 3.0,
        optimalTemp: 18,
        description: "Requires well-drained soil.",
      },
      {
        name: "Wheat",
        nameAr: "قمح",
        minMoisture: 15,
        maxMoisture: 50,
        minSalinity: 4.0,
        maxSalinity: 8.0,
        optimalTemp: 20,
        description: "Moderate water needs.",
      },
      {
        name: "Corn",
        nameAr: "ذرة",
        minMoisture: 25,
        maxMoisture: 65,
        minSalinity: 1.5,
        maxSalinity: 3.5,
        optimalTemp: 28,
        description: "High nitrogen and water needs.",
      },
      {
        name: "Rice",
        nameAr: "أرز",
        minMoisture: 60,
        maxMoisture: 95,
        minSalinity: 2.0,
        maxSalinity: 4.0,
        optimalTemp: 30,
        description: "Requires flooded soil.",
      },
      {
        name: "Strawberry",
        nameAr: "فراولة",
        minMoisture: 35,
        maxMoisture: 75,
        minSalinity: 0.5,
        maxSalinity: 1.5,
        optimalTemp: 20,
        description: "Needs frequent watering.",
      },
      {
        name: "Onion",
        nameAr: "بصل",
        minMoisture: 20,
        maxMoisture: 55,
        minSalinity: 1.0,
        maxSalinity: 2.0,
        optimalTemp: 18,
        description: "Sensitive to overwatering.",
      },
      {
        name: "Garlic",
        nameAr: "ثوم",
        minMoisture: 15,
        maxMoisture: 50,
        minSalinity: 1.0,
        maxSalinity: 2.5,
        optimalTemp: 15,
        description: "Moderate water needs.",
      },
      {
        name: "Pepper",
        nameAr: "فلفل",
        minMoisture: 30,
        maxMoisture: 70,
        minSalinity: 1.0,
        maxSalinity: 2.0,
        optimalTemp: 26,
        description: "Needs warm soil.",
      },
      {
        name: "Eggplant",
        nameAr: "باذنجان",
        minMoisture: 30,
        maxMoisture: 70,
        minSalinity: 1.5,
        maxSalinity: 3.0,
        optimalTemp: 27,
        description: "Heavy feeder.",
      },
      {
        name: "Lettuce",
        nameAr: "خس",
        minMoisture: 40,
        maxMoisture: 85,
        minSalinity: 1.0,
        maxSalinity: 2.0,
        optimalTemp: 16,
        description: "Needs cool soil.",
      },
      {
        name: "Carrot",
        nameAr: "جزر",
        minMoisture: 25,
        maxMoisture: 60,
        minSalinity: 1.0,
        maxSalinity: 2.5,
        optimalTemp: 18,
        description: "Requires loose soil.",
      },
      {
        name: "Cabbage",
        nameAr: "كرنب",
        minMoisture: 35,
        maxMoisture: 75,
        minSalinity: 1.5,
        maxSalinity: 3.5,
        optimalTemp: 17,
        description: "Heavy water user.",
      },
      {
        name: "Watermelon",
        nameAr: "بطيخ",
        minMoisture: 20,
        maxMoisture: 60,
        minSalinity: 1.5,
        maxSalinity: 4.0,
        optimalTemp: 28,
        description: "Deep roots.",
      },
      {
        name: "Mango",
        nameAr: "مانجو",
        minMoisture: 15,
        maxMoisture: 45,
        minSalinity: 1.0,
        maxSalinity: 3.0,
        optimalTemp: 32,
        description: "Drought tolerant.",
      },
      {
        name: "Citrus",
        nameAr: "موالح",
        minMoisture: 20,
        maxMoisture: 55,
        minSalinity: 1.5,
        maxSalinity: 3.5,
        optimalTemp: 25,
        description: "Needs consistent water.",
      },
      {
        name: "Grapes",
        nameAr: "عنب",
        minMoisture: 15,
        maxMoisture: 40,
        minSalinity: 1.5,
        maxSalinity: 3.0,
        optimalTemp: 24,
        description: "Needs deep watering.",
      },
      {
        name: "Olive",
        nameAr: "زيتون",
        minMoisture: 10,
        maxMoisture: 35,
        minSalinity: 3.0,
        maxSalinity: 6.0,
        optimalTemp: 26,
        description: "Very drought tolerant.",
      },
      {
        name: "Cotton",
        nameAr: "قطن",
        minMoisture: 20,
        maxMoisture: 60,
        minSalinity: 4.0,
        maxSalinity: 10.0,
        optimalTemp: 30,
        description: "Heat lover.",
      },
    ];

    for (const crop of crops) {
      await ctx.db.insert("plants", crop);
    }
    return { message: "Seeding complete", count: crops.length };
  },
});
